export  const members = [
   {
      id: 1,
      name: "Himanshu Dubey",
      branch: "BTech IT 4th Year",
      designation: "HimanshuDubey.jpg",
      image:"",
      linkedin: "https://www.linkedin.com/in/himanshud2611?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
   },
   {
      id: 2,
      name: "Krishna Nand",
      branch: "MCA 2nd Year",
      designation: "Student Joint Treasurer",
      image: "KrishnaNand.jpg",
      linkedin: "https://www.linkedin.com/in/krishna-nand-kn?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
   },
   {
      id: 3,
      name: "Utkarsh Tiwari",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "UtkarshTiwari.jpg",
      linkedin: "https://www.linkedin.com/in/imutkarsht",
   },
   {
      id: 4,
      name: "Ahmad Faraz Ansari",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "AhmadFarazAnsari.jpg",
      linkedin: "https://www.linkedin.com/in/frzansari20",
   },
   {
      id: 5,
      name: "Shrey Srivastava",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "ShreySrivastava.jpg",
      linkedin: "https://www.linkedin.com/in/shreysrivastava01",
   },
   {
      id: 6,
      name: "Sachin Chauhan",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "SachinChauhan.jpg",
      linkedin: "https://www.linkedin.com/in/sachinchauhan010",
   },
   {
      id: 7,
      name: "Divyanshu Kanaujiya",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "DivyanshuKanaujiya.jpg",
      linkedin: "https://www.linkedin.com/in/divyanshukanaujia",
   },
   {
      id: 8,
      name: "Rupali Mishra",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "RupaliMishra.jpg",
      linkedin: "https://www.linkedin.com/in/rupali-mishra-b91121295?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
   },
   {
      id: 9,
      name: "Siddhi Mishra",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "SiddhiMishra.jpg",
      linkedin: "https://www.linkedin.com/in/siddhi-mishra-31b516295?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
   },
   {
      id: 10,
      name: "Sanchita Bajpai",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "SanchitaBajpai.jpg",
      linkedin: "http://www.linkedin.com/in/sanchita-bajpai-867582230",
   },

   {
      id: 11,
      name: "Abhishrestha Tiwari",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "AbhishresthaTiwari.jpg",
      linkedin: "https://www.linkedin.com/in/abhi2330?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
   },
   {
      id: 12,
      name: "Aditya Tripathi",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "AdityaTripathi.jpg",
      linkedin: "https://www.linkedin.com/in/aditya-tripathi-85bb60257/",
   },
   {
      id: 13,
      name: "Amit Kumar Sahani",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "AmitKumarSahani.jpg",
      linkedin: "https://www.linkedin.com/in/amitsahani19/",
   },

   {
      id: 14,
      name: "Anshul Sengar",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "AnshulSengar.jpg",
      linkedin: "https://www.linkedin.com/in/anshul-sengar-116a7b257/",
   },
   {
      id: 15,
      name: "Himani Rajput",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "HimaniRajput.jpg",
      linkedin: "",
   },
   {
      id: 16,
      name: "Kumari Nisha",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "KumariNisha.jpg",
      linkedin: "https://www.linkedin.com/in/kumari-nisha-286932278",
   },
   {
      id: 17,
      name: "Manoj Kumar",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "ManojKumar.jpg",
      linkedin: "https://www.linkedin.com/in/manoj-kumar-355777262?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
   },
   {
      id: 18,
      name: "Priya Yadav",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "PriyaYadav.jpg",
      linkedin: "https://www.linkedin.com/in/py1703",
   },
   {
      id: 19,
      name: "Vishesh Singh",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "VisheshSingh.jpg",
      linkedin: "https://www.linkedin.com/in/visheshjnp",
   },
   {
      id: 20,
      name: "Alabhya Goel",
      branch: "BTech IT 4th Year",
      designation: "Executive Member",
      image: "AlabhyaGoel.jpg",
      linkedin: "https://www.linkedin.com/in/alabhya-goel?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
   },
   {
      id: 21,
      name: "Komal Gupta",
      branch: "BTech IT 4th Year",
      designation: "Executive Member",
      image: "KomalGupta.jpg",
      linkedin: "https://www.linkedin.com/in/komal-gupta-61b72b228",
   },
   {
      id: 22,
      name: "Perneeta Awasthi",
      branch: "BTech IT 4th Year",
      designation: "Executive Member",
      image: "PerneetaAwasthi.jpg",
      linkedin: "https://www.linkedin.com/in/parineeta-awasthi-0459a3229",
   },
   {
      id: 23,
      name: "Shristi Singh",
      branch: "BTech IT 4th Year",
      designation: "Executive Member",
      image: "ShristiSingh.jpg",
      linkedin: "https://www.linkedin.com/in/shristi-singh-234b61259",
   },
   {
      id: 24,
      name: "Vaibhav Garg",
      branch: "BTech IT 4th Year",
      designation: "Executive Member",
      image: "VaibhavGarg.jpg",
      linkedin: "https://www.linkedin.com/in/vaibhav0207?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
   },
   {
      id: 25,
      name: "Aaditya Upadhyay",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "AadityaUpadhyay.jpg",
      linkedin: "https://www.linkedin.com/in/aaditya-upadhyay-53341b299?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
   },
   {
      id: 26,
      name: "Aditi Yadav",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "AditiYadav.jpg",
      linkedin: "https://www.linkedin.com/in/aditi-yadav-7b6bb0302?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
   },
   {
      id: 27,
      name: "Akash Gupta",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "AkashGupta.jpg",
      linkedin: "https://www.linkedin.com/in/akash-gupta-b33559278/",
   },
   {
      id: 28,
      name: "Riya Srivastava",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "RiyaSrivastava.jpg",
      linkedin: "https://www.linkedin.com/in/riya-srivastava-610629294?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
   },
   {
      id: 29,
      name: "Ryan Maroof",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "RyanMaroof.jpg",
      linkedin: "https://www.linkedin.com/in/ryan-maroof-547ba728b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
   },
   {
      id: 30,
      name: "Sandhya Kumari",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "SandhyaKumari.jpg",
      linkedin: "https://www.linkedin.com/in/sandhya-kumari-2a8634294?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
   },
   {
      id: 31,
      name: "Saumya Srivastava",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "SaumyaSrivastava.jpg",
      linkedin: "https://www.linkedin.com/in/saumya-srivastava-6909b1294?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
   },
   {
      id: 32,
      name: "Shashank Bharadwaj",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "ShashankBharadwaj.jpg",
      linkedin: "https://www.linkedin.com/in/shashank-bhardwaj-180060291?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
   },
   {
      id: 33,
      name: "Shivankar Tripathi",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "ShivankarTripathi.jpg",
      linkedin: "https://www.linkedin.com/in/introversh",
   },
   {
      id: 34,
      name: "Vaishnavi Tripathi",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "VaishnaviTripathi.jpg",
      linkedin: "http://www.linkedin.com/in/vaishnavi-tripathi-a37469282",
   },
];