export const members = [
   {
      id: 1,
      name: "Himanshu Dubey",
      branch: "BTech IT 4th Year",
      designation: "Student Secretary",
      image: "https://picsum.photos/1080/720",
      linkedin: "https://www.linkedin.com/in/himanshud2611/",
   },
   {
      id: 2,
      name: "Krishna Nand",
      branch: "MCA 2nd Year",
      designation: "Student Joint Treasurer",
      image: "https://picsum.photos/1080/720",
      linkedin: "https://www.linkedin.com/in/krishna-nand-kn/",
   },
   {
      id: 3,
      name: "Utkarsh Tiwari",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "https://www.linkedin.com/in/imutkarsht/",
   },
   {
      id: 4,
      name: "Ahmad Faraz Ansari",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "https://www.linkedin.com/in/frzansari20/",
   },
   {
      id: 5,
      name: "Shrey Srivastava",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "https://www.linkedin.com/in/shreysrivastava01/",
   },
   {
      id: 6,
      name: "Sachin Chauhan",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "https://www.linkedin.com/in/sachinchauhan010/",
   },
   {
      id: 7,
      name: "Divyanshu Kanaujiya",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "https://www.linkedin.com/in/divyanshukanaujia/",
   },
   {
      id: 8,
      name: "Rupali Mishra",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "https://www.linkedin.com/in/rupali-mishra-b91121295/",
   },
   {
      id: 9,
      name: "Siddhi Mishra",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "https://www.linkedin.com/in/siddhi-mishra-31b516295/",
   },
   {
      id: 10,
      name: "Sanchita Bajpai",
      branch: "MCA 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "https://www.linkedin.com/in/sanchita-bajpai-867582230/",
   },

   {
      id: 11,
      name: "Abhishrestha Tiwari",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "https://www.linkedin.com/in/abhi2330",
   },
   {
      id: 12,
      name: "Aditya Tripathi",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "https://www.linkedin.com/in/aditya-tripathi-85bb60257/",
   },
   {
      id: 13,
      name: "Amit Kumar Sahani",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "https://drive.google.com/uc?export=view&id=1JEcHiyWlGPr0yX3np1OiuWCd5DBCZaJ4",
      linkedin: "https://www.linkedin.com/in/amitsahani19/",
   },

   {
      id: 14,
      name: "Anshul Sengar",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "https://www.linkedin.com/in/anshul-sengar-116a7b257/",
   },
   {
      id: 15,
      name: "Himani Rajput",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 16,
      name: "Kumari Nisha",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 17,
      name: "Manoj Kumar",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 18,
      name: "Priya Yadav",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 19,
      name: "Vishesh Singh",
      branch: "BTech IT 3rd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 20,
      name: "Alabhya Goel",
      branch: "BTech IT 4th Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 21,
      name: "Komal Gupta",
      branch: "BTech IT 4th Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 22,
      name: "Perneeta Awasthi",
      branch: "BTech IT 4th Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 23,
      name: "Shristi Singh",
      branch: "BTech IT 4th Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 24,
      name: "Vaibhav Garg",
      branch: "BTech IT 4th Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 25,
      name: "Aaditya Upadhyay",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 26,
      name: "Aditi Yadav",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 27,
      name: "Akash Gupta",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 28,
      name: "Riya Srivastava",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 29,
      name: "Ryan Maroof",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 30,
      name: "Sandhya Kumari",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 31,
      name: "Saumya Srivastava",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 32,
      name: "Shashank Bharadwaj",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 33,
      name: "Shivankar Tripathi",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
   {
      id: 34,
      name: "Vaishnavi Tripathi",
      branch: "BTech IT 2nd Year",
      designation: "Executive Member",
      image: "https://picsum.photos/1080/720",
      linkedin: "",
   },
];